### ISSUE TITLE
All emails show as conversations, with a '2' badge

### ISSUE THREAD

**Issue by Lissy93** [CTemplar/ios#100]
A user on Reddit has reported that all their emails have a corresponding number 2 (as in two emails in that conversation), even when there is only 1 message in that chain.

<details><summary>Screenshot</summary>
<img src="https://i.imgur.com/pLr96Rk.jpg"/>
</details>

Thanks,
Alicia

- Device: iPad Pro model A1673, iOS version 14.4.2, CTemplar version 1.4.9 (2).
- [Screenshot](https://i.imgur.com/pLr96Rk.jpg)
- [Relevant Reddit Thread](https://www.reddit.com/r/ctemplar/comments/mql8mh/what_is_the_2/)
- Possibly caused by how messages are counted in [`InboxMessageTablelViewCell+Labels.swift`](https://github.com/CTemplar/ios/blob/master/Modules/Inbox/Inbox/Views/InboxMessageTablelViewCell+Labels.swift#L53)

---
### Environment

Device: iPad Pro model A1673 and another user on iPhone 12
iOS version: 14.4.2
CTemplar version: 1.4.9 (2).

### Steps to reproduce

1. Open app, see emails, single emails have a number 2 next to each

### Expected behavior

If a single email, then expected not to see any number. If there are 2 or more messages in a given chain, then expect to see a number corresponding to the number of emails

### Actual behavior
A Number 2 is shown always, even when there is only a single message in a chain

**Comment by The-Hidden-Hand** [comment]
@nivritgupta 
FYI.

**Comment by nivritgupta** [comment]
@The-Hidden-Hand   i am checking this issue.
