### ISSUE TITLE
HTML templates sometimes show the bigger text (appleid verification template example )

### ISSUE THREAD

**Issue by nivritgupta** [CTemplar/ios#147]
I noticed recent apple verification HTML templates showing bigger text.  this will happen only with apple mails, I am checking this issue.

![IMG_1DFE1097F2C2-1](https://user-images.githubusercontent.com/1904874/127445073-4a82ace4-73ed-4c69-a1f5-15b0791d328a.jpeg)

**Comment by The-Hidden-Hand** [comment]
@nivritgupta 
Users were complaining by this a lot in the past, so I'm glad you were able to reproduce.
