### ISSUE TITLE
Share option in text

### ISSUE THREAD

**Issue by nivritgupta** [CTemplar/ios#186]
Add share option in the selected text.
![IMG_0230](https://user-images.githubusercontent.com/1904874/140681372-718f3ef8-46fe-47bb-923f-fb318bec17af.PNG)

 
![IMG_0231](https://user-images.githubusercontent.com/1904874/140681490-b4c18ba0-de08-4fcc-a0d2-cc6965f42196.PNG)

**Comment by The-Hidden-Hand** [comment]
I think this was done but it stills InProgress?
Shall we move it forward? @nivritgupta

**Comment by nivritgupta** [comment]
@The-Hidden-Hand  yes
