### ISSUE TITLE
I imported a public key (generated from Proton Mail) for the contact in ctemplar. (Testet with ECC an 4096) The Web-Client works fine, in the IOS-App the mails can not be decrypted. It seems, as IOS has no keys.

### ISSUE THREAD

**Issue by nivritgupta** [CTemplar/ios#192]

**Comment by nivritgupta** [comment]
today I tested the application with protonmail keys, however, I found no issue, I have one protonmail account, I download the private keys from protonmail and import them in ctemplar application
and on IOS application private (ECC key) appear successfully
even I tried to send 5,6 emails and I am able to decrypt the mails successfully using newly generated keys.

**Comment by The-Hidden-Hand** [comment]
What else then?
