### ISSUE TITLE
'Share with CTemplar' option

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/ios#91]
### Expected behavior

Make the CTemplar app an option to share content with.

Reference: https://user-images.githubusercontent.com/45569116/106476587-20ee5500-649f-11eb-99e1-d67c2d905c32.png

**Comment by The-Hidden-Hand** [comment]
@nivritgupta 
It is to share content from OTHER apps sending a CTemplar email.

**Comment by nivritgupta** [comment]
@The-Hidden-Hand , will you please let me know in detail  where should I add share option??, i already created a control for share anything

**Comment by The-Hidden-Hand** [comment]
@alexdwork2018 ?
