### ISSUE TITLE
Self-destructing emails function is not well understood

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/ios#95]
### Expected behavior

Self-destructing emails is confusing users.

1. Indicate it will only apply to CTemplar recipients when adding external recipients.
3. Optional: Disable if none recipient is CTemplar.

**Comment by alexdwork2018** [comment]
@The-Hidden-Hand hi . Yes, this message (Self-destructing emails function is not well understood) seems weird. This message was copied from the corresponding logic on the Web Client. Can you please propose the proper text here? It should reflect the situation that the sender wants to send self-destructing message to the recipients outside CTemplar. So the destruction can not be granted. Or you can propose the change into this logic

**Comment by alexdwork2018** [comment]
@The-Hidden-Hand I double-checked the behavior of this function in the Android app. The message "Self Destruction is only for CTemplar recipients. Please add CTemplar recipients for self-destruction feature" is displayed only if none of the recipients is a CTemplar address. Do I need to change the logic of this function, or if its behavior is right can I move the task to the done section?

**Comment by The-Hidden-Hand** [comment]
@alexdwork2018 
That should be fine. With an screenshot I could tell you better but sounds good.
